[config]
version_check = false

[templates.m3colors]
input_path = '~/.config/matugen/templates/colors.json'
output_path = '~/.local/state/quickshell/user/generated/colors.json'

[templates.hyprland]
input_path = '~/.config/matugen/templates/hyprland/colors.lua'
output_path = '~/.config/hypr/hyprland/colors.lua'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprland/hyprlock-colors.conf'
output_path = '~/.config/hypr/hyprlock/colors.conf'

[templates.fuzzel]
input_path = '~/.config/matugen/templates/fuzzel/fuzzel_theme.ini'
output_path = '~/.config/fuzzel/fuzzel_theme.ini'

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-3.0/gtk.css'
output_path = '~/.config/gtk-3.0/gtk.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-4.0/gtk.css'
output_path = '~/.config/gtk-4.0/gtk.css'

[templates.kde_colors]
input_path = '~/.config/matugen/templates/kde/color.txt'
output_path = '~/.local/state/quickshell/user/generated/color.txt'

[templates.wallpaper]
input_path = '~/.config/matugen/templates/wallpaper.txt'
output_path = '~/.local/state/quickshell/user/generated/wallpaper/path.txt'

[templates.vicinae]
input_path = './templates/vicinae.toml'
output_path = '~/.local/share/vicinae/themes/matugen.toml'
post_hook = 'vicinae theme set matugen'

[templates.fzf]
input_path = "~/.config/matugen/templates/fzf.sh"
output_path = "~/.config/fzf/fzf-matugen.sh"

[templates.thunderbird]
input_path = '~/.config/matugen/templates/thunderbird.css'
output_path = '~/.config/matugen/thunderbird.css'

[templates.vesktop]
input_path = '~/.config/matugen/templates/vesktop/vesktop.css'
output_path = '~/.config/vesktop/themes/matugen.css'

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux/tmux.conf'
output_path = '~/.config/tmux/matugen-colors.conf'
post_hook = 'tmux source-file ~/.config/tmux/matugen-colors.conf'

[templates.zed]
input_path = '~/.config/matugen/templates/zed.json'
output_path = '~/.config/zed/themes/matugen-blur.json'

[templates.chatterino]
input_path = '~/.config/matugen/templates/chatterino/matugen.json'
output_path = '~/.local/share/chatterino/Themes/matugen.json'

[templates.btop]
input_path = '~/.config/matugen/templates/btop/matugen.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.cava]
input_path = '~/.config/matugen/templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

[templates.helix]
input_path = '~/.config/matugen/templates/helix/matugen.toml'
output_path = '~/.config/helix/themes/matugen.toml'

[templates.neovim]
input_path = '~/.config/matugen/templates/neovim/matugen.lua'
output_path = '~/.config/nvim/matugen.lua'
post_hook = 'pkill -SIGUSR1 nvim'

[templates.opencode]
input_path = '~/.config/matugen/templates/opencode.json'
output_path = '~/.config/opencode/themes/matugen.json'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi/theme.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.obs]
input_path = '~/.config/matugen/templates/obs/matugen.obt'
output_path = '~/.config/obs-studio/themes/matugen.obt'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian/matugen.css'
output_path = '/home/lenox/Documents/notes/NOTES/.obsidian/snippets/matugen.css'

[templates.spotify]
input_path = '~/.config/matugen/templates/spicetify/color.ini'
output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'

[templates.zellij]
input_path = '~/.config/matugen/templates/zellij/matugen.kdl'
output_path = '~/.config/zellij/themes/matugen.kdl'
post_hook = 'touch ~/.config/zellij/config.kdl'
