modmap:
  # Minecraft
  - name: Minecraft Sprint Override
    application:
      only: "com.mojang.minecraft"
    remap:
      CAPSLOCK: CTRL_L

  # Android Keyboard over sunshine
  - name: "Fix Android Keyboard"
    device:
      only:
        - "RustDesk UInput Keyboard"
        - "Keyboard passthrough"
    remap:
      GRAVE: ESC
      ALT_L: SUPER_L
      CAPSLOCK: ALT_L

# Dolphin Right Click Shortcut
keymap:
  # - name: Global Sanity Check
  #   application:
  #     only: "org.kde.dolphin"
  #   remap:
  #     Alt_R: VolumeUp

  - name: Dolphin Right Click Shortcut
    application:
      only: "org.kde.dolphin"
    remap:
      C-z: Shift-F10
