-- Generated by Matugen

require('base16-colorscheme').setup({
    base00 = "#1a110f",
    base01 = "#140c0a",
    base02 = "#231917",
    base03 = "#53433f",
    base04 = "#d8c2bc",
    base05 = "#f1dfda",
    base06 = "#392e2b",
    base07 = "#423734",

    base08 = "#d2bd7a",
    base09 = "#d8c68d",
    base0A = "#e7bdb1",
    base0B = "#ffb59e",
    base0C = "#52461a",
    base0D = "#723521",
    base0E = "#5d4037",
    base0F = "#db9c8a",
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
    for _, v in pairs(groups) do
        vim.api.nvim_set_hl(0, v, value)
    end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
    bg = '#723521',
    fg = '#ffdbd0', -- normal text contrast
})

-- Make "string" text contrast better
set_hl_mutliple({ 'String', 'TSString' }, {
    fg = '#c5aa54',
})

-- Grey out comments
set_hl_mutliple({ 'TSComment', 'Comment' }, {
    fg = '#a08c87',
    italic = true,
})

-- Color in other highlight groups as you see fit!

set_hl_mutliple({ 'TSMethod', 'Method' }, {
    fg = '#d8c68d',
})


set_hl_mutliple({ 'TSFunction', 'Function' }, {
    fg = '#e7bdb1',
})

set_hl_mutliple({ 'Keyword', 'TSKeyword', 'TSKeywordFunction', 'TSRepeat' }, {
    fg = '#8f4c36',
})
